### ISSUE TITLE
Bug Report: Missing Icon

### ISSUE THREAD

**Issue by sinansays** [swarajban/tab-notes#4]
Some Chrome windows will have tabs that stop displaying the Tab Notes icon over time. If I open a new window, the tabs in that window will strangely have the icon. Somehow the existing tabs "forget" over time.

**Comment by swarajban** [comment]
Sry @sinansays, these just didn't make it into our product road map

**Comment by sinansays** [comment]
Haha it's safe to say that tab-notes has been sunsetted by now :-P
